"""Copy the stored trades into the video project as a typed module.

Written as a .ts file rather than JSON so the bundler needs no extra
configuration, and so the video always renders whatever the journal last
ingested. Run this before rendering.
"""
import io
import json
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, "..", "journal_data", "trades.json")
OUT = os.path.join(ROOT, "src", "trades.ts")

ONLY = "live"     # the library is for learning from YOUR trading

# The store now holds four sources: your live trades, hand-placed paper trades,
# replay practice, and the automated system's. Left unfiltered the videos blended
# all of them, so a "Monday" cut carried your five trades AND the system's from
# the same day, and a date you never traded turned up as a session of yours.
# The diary is careful to keep these apart and the library has to be too.
trades = [t for t in json.load(io.open(SRC, encoding="utf-8"))
          if t.get("source", "live") == ONLY]
if not trades:
    print(f"No '{ONLY}' trades on record yet, so there is nothing to film.")
    raise SystemExit(0)
keep = ("symbol", "side", "qty", "open_t", "close_t", "entry", "exit", "stop",
        "target", "risk_pts", "planned_rr", "got_r", "got_pts", "pnl", "mfe_r",
        "mae_r", "kept_pct", "held_min", "exit_type", "flags", "note", "trail",
        "bars", "entry_i", "exit_i")
slim = [{k: t[k] for k in keep if k in t} for t in trades]

body = json.dumps(slim, indent=1)
io.open(OUT, "w", encoding="utf-8").write(
    "// Generated by build_data.py. Do not edit by hand.\n"
    "import type {Trade} from './types';\n\n"
    f"export const TRADES: Trade[] = {body};\n")
print(f"{len(slim)} trades -> src/trades.ts")
